services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    environment:
		MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
		MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    depends_on: [mongo]
    ports: ["8085:8081"]
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/?authSource=admin

  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yaml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/kong.yaml:/opt/kong/kong.yaml:ro
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin
   
volumes:
  mongo_data:
