spring.application.name=projectUserKongGraphQL

server.port=8081
spring.aplication.name= user-service


spring.data.mongodb.uri=mongodb://user:pass@localhost:27017/userdb?authSource=admin


spring.graphql.graphiql.enabled=true

spring.data.mongodb.database=usersdb
